# Generated by Django 4.0.2 on 2022-03-16 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ability name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.CharField(default='0', max_length=50, verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='BattlefieldRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='detachment role name')),
            ],
        ),
        migrations.CreateModel(
            name='CodexFaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='codex faction name')),
            ],
        ),
        migrations.CreateModel(
            name='FactionKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='faction keyword name')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='keyword name')),
            ],
        ),
        migrations.CreateModel(
            name='OtherWargear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='wargear name')),
                ('description', models.TextField(verbose_name='wargear description')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='unit name')),
                ('wargear_options', models.TextField(blank=True, default='', verbose_name='wargear options')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('power_rating', models.PositiveIntegerField(verbose_name='power rating')),
                ('picture_search_link', models.URLField(blank=True, default='', verbose_name='picture search link')),
                ('transport', models.TextField(blank=True, default='', verbose_name='transport')),
                ('psyker', models.TextField(blank=True, default='', verbose_name='psyker')),
                ('warlord_trait', models.TextField(blank=True, default='', verbose_name='warlord trait')),
                ('abilities', models.ManyToManyField(blank=True, related_name='abilities', to='builder.Ability', verbose_name='abilities')),
                ('battlefield_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.battlefieldrole')),
                ('codex_faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codex_faction', to='builder.codexfaction', verbose_name='codex faction')),
                ('faction_keywords', models.ManyToManyField(blank=True, related_name='faction_keywords', to='builder.FactionKeyword', verbose_name='faction_keywords')),
                ('keywords', models.ManyToManyField(blank=True, related_name='keywords', to='builder.Keyword', verbose_name='keywords')),
                ('other_wargear', models.ManyToManyField(related_name='other_wargear', to='builder.OtherWargear', verbose_name='other_wargear')),
            ],
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='unit name')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='weapon ability name')),
                ('price', models.CharField(default='0', max_length=50, verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='single', max_length=250, verbose_name='weapon profile name')),
                ('weapon_range', models.CharField(blank=True, max_length=100, verbose_name='weapon range')),
                ('weapon_type', models.CharField(blank=True, max_length=100, verbose_name='weapon type')),
                ('strength', models.CharField(blank=True, max_length=100, verbose_name='strength')),
                ('armor_penetration', models.CharField(blank=True, max_length=100, verbose_name='armor penetration')),
                ('damage', models.CharField(blank=True, max_length=100, verbose_name='damage')),
                ('abilities', models.TextField(blank=True, verbose_name='abilities')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wp_weapon', to='builder.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='UnitsCountRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_count', models.PositiveIntegerField(default=0, verbose_name='minimum count')),
                ('maximum_count', models.PositiveIntegerField(blank=True, verbose_name='maximum count')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucr_unit', to='builder.unit')),
                ('unit_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_model', to='builder.unitmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UnitModelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='position')),
                ('movement', models.CharField(blank=True, max_length=100, verbose_name='movement')),
                ('weapon_skill', models.PositiveIntegerField(blank=True, verbose_name='weapon skill')),
                ('ballistic_skill', models.CharField(blank=True, max_length=50, verbose_name='ballistic_skill')),
                ('strength', models.CharField(blank=True, max_length=100, verbose_name='strength')),
                ('toughness', models.PositiveIntegerField(blank=True, verbose_name='toughness')),
                ('wounds', models.CharField(blank=True, max_length=100, verbose_name='wounds')),
                ('attacks', models.CharField(blank=True, max_length=100, verbose_name='attacks')),
                ('leadership', models.PositiveIntegerField(blank=True, verbose_name='leadership')),
                ('saving_throw', models.PositiveIntegerField(blank=True, verbose_name='saving throw')),
                ('base', models.CharField(blank=True, max_length=50, verbose_name='base')),
                ('unit_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ump_unit', to='builder.unitmodel', verbose_name='unit')),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='weapon',
            field=models.ManyToManyField(blank=True, related_name='u_weapon', to='builder.Weapon', verbose_name='weapon'),
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='unit name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('total_cost', models.PositiveIntegerField(default=0, verbose_name='total roster cost')),
                ('max_cost', models.PositiveIntegerField(default=1500, verbose_name='maximum roster cost')),
                ('private', models.BooleanField(default=False)),
                ('roster_data', models.BinaryField(null=True, verbose_name='roster data')),
                ('factions', models.ManyToManyField(related_name='factions', to='builder.CodexFaction', verbose_name='factions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
