# Generated by Django 4.0.2 on 2022-02-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitmodelprofile',
            old_name='unit',
            new_name='unit_model',
        ),
    ]
