# Generated by Django 4.0.2 on 2022-02-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_rename_unit_unitmodelprofile_unit_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmodelprofile',
            name='attacks',
            field=models.CharField(blank=True, max_length=100, verbose_name='attacks'),
        ),
        migrations.AlterField(
            model_name='unitmodelprofile',
            name='movement',
            field=models.CharField(blank=True, max_length=100, verbose_name='movement'),
        ),
        migrations.AlterField(
            model_name='unitmodelprofile',
            name='strength',
            field=models.CharField(blank=True, max_length=100, verbose_name='strength'),
        ),
        migrations.AlterField(
            model_name='unitmodelprofile',
            name='wounds',
            field=models.CharField(blank=True, max_length=100, verbose_name='wounds'),
        ),
    ]
