# Generated by Django 4.0.2 on 2022-04-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_detachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='roster_data',
            field=models.BinaryField(default=b'{"detachment_data": [], "main_data": []}', null=True, verbose_name='roster data'),
        ),
    ]
